## Laboratory Task 5: NumPy & PyTorch Tensor Operations

1. **Perform Standard Imports**
2. **Create `set_seed()` Function**: Accepts `seed: int` as a parameter to set the random seed.
3. **Create NumPy Array `arr`**: Contains 6 random integers between 0 (inclusive) and 5 (exclusive) using seed 42.
4. **Create Tensor `x`**: Convert `arr` into a PyTorch tensor.
5. **Change `dtype`**: Convert `x` from `int32` to `int64`.
6. **Reshape `x`**: Reshape `x` into a $3 \times 2$ tensor.
7. **Extract Column**: Return the right-hand column of tensor `x`.
8. **Square Values**: Return a tensor of square values of `x` without mutating `x`.
9. **Create Tensor `y`**: Generate a tensor with the same number of elements as `x` (6 elements) using PyTorch with random integers between 0 and 5 (seed 42), shaped appropriately to allow matrix multiplication $x \cdot y$.
10. **Matrix Multiplication**: Compute the matrix product of `x` and `y`.

In [1]:
# 1. Perform Standard Imports
import numpy as np
import torch

# 2. Create set_seed function
def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)

# 3. Create NumPy array "arr" with 6 random integers between 0 (inc) and 5 (exc) using seed 42
set_seed(42)
arr = np.random.randint(0, 5, size=6)
print("3. Array 'arr':\n", arr)

# 4. Create a tensor "x" from the array above
x = torch.from_numpy(arr)
print("\n4. Tensor 'x':\n", x)

# 5. Change the dtype of x from int32 to int64
x = x.type(torch.int64)
print("\n5. Tensor 'x' dtype:\n", x.dtype)

# 6. Reshape x into a 3x2 tensor
x = x.reshape(3, 2)
print("\n6. Reshaped x (3x2):\n", x)

# 7. Return the right-hand column of tensor x
right_column = x[:, 1]
print("\n7. Right-hand column of x:\n", right_column)

# 8. Without changing x, return a tensor of square values of x
x_squared = x ** 2
print("\n8. Square values of x:\n", x_squared)

# 9. Create tensor y with same number of elements (6) that can be matrix-multiplied with x (3x2).
# Shape of y must be (2, 3) so that (3x2) @ (2x3) -> (3x3)
set_seed(42)
y = torch.randint(low=0, high=5, size=(2, 3), dtype=torch.int64)
print("\n9. Tensor 'y' (2x3):\n", y)

# 10. Find the matrix product of x and y
matrix_product = torch.matmul(x, y)
print("\n10. Matrix product of x and y (3x3):\n", matrix_product)

3. Array 'arr':
 [3 4 2 4 4 1]

4. Tensor 'x':
 tensor([3, 4, 2, 4, 4, 1])

5. Tensor 'x' dtype:
 torch.int64

6. Reshaped x (3x2):
 tensor([[3, 4],
        [2, 4],
        [4, 1]])

7. Right-hand column of x:
 tensor([4, 4, 1])

8. Square values of x:
 tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

9. Tensor 'y' (2x3):
 tensor([[2, 2, 1],
        [4, 1, 0]])

10. Matrix product of x and y (3x3):
 tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
